#!/bin/sh

sudo apt update -y

sudo apt upgrade -y

sudo apt install openssh-server -y

sudo apt install nginx -y
systemctl start nginx
systemctl enable nginx

sudo apt install php-fpm php-mcrypt php-curl php-cli php-mysql php-gd php-xsl php-json php-intl php-pear php-dev php-common php-mbstring php-tidy php-zip php-soap libcurl3 curl -y

sudo apt install mariadb-server mariadb
