#!/bin/sh

#init
function pause() {
  read -p "$*"
}

systemctl status nginx
netstat - plntu
pause 'Verify nginx services then press [Enter]'

systemctl start php7.0-fpm
systemctl enable php7.0-fpm
netstat -pl | grep fpm
pause 'Verify php7.0-fpm.sock then press [Enter]'

#Download\Install PHP Composer and make a system-wide command named composer
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
#verify hash
php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"

pause 'Verify installer validity then press [Enter]'
pause '***If installer is corrupt, EXIT SCRIPT!!!*** To continue [Enter]'

sudo php composer-setup.php --install-dir=/usr/local/bin --filename=composer

#Install BookStack
cd /var/www/
sudo git clone https://github.com/BookStackApp/BookStack.git --branch release --single-branch

#Install PHP dependencies
cd /var/www/BookStack/
sudo composer install -y
